import { BG_HEX } from "../constants/style";

// Season-based gradient theme
const SEASON_COLORS = {
  spring: ["#1a4a2e", "#e8a0bf", "#3d9e5c", "#d4f0c6"],
  summer: ["#f5a623", "#1a8fe0", "#ff6b35", "#08b4a8"],
  fall: ["#8b2500", "#d85a30", "#f5a623", "#4a1b0c"],
  winter: ["#2c3e6b", "#a0c4e8", "#4a6fa5", "#d0e8f5"],
};
export function getCurrentSeason() {
  const m = new Date().getMonth();
  if (m >= 2 && m <= 4) return "spring";
  if (m >= 5 && m <= 7) return "summer";
  if (m >= 8 && m <= 10) return "fall";
  return "winter";
}
const _sc = SEASON_COLORS[getCurrentSeason()];

export const DEFAULTS = {
  sphereRadius: 0.7,
  sphereDetail: 64,
  shapeScale: 0.95,
  rotationSpeed: 0.15,
  shapeTiltX: 0.3,
  shapeTiltY: 0.5,
  noiseFreq: 0.2,
  noiseAmp: 3.25,
  noiseSpeed: 0.95,
  noiseOctaves: 2,
  noiseLacunarity: 4,
  noisePersistence: 0.9,
  spikeSharpness: 6,
  noiseWarp: 0.85,
  mouseStrength: 0.2,
  mouseRadius: 2,
  mouseFalloff: 1.2,
  mouseNoiseBoost: 0.4,
  mouseNoiseFreq: 2.6,
  mouseAttract: -2,
  baseBrightStart: 1.8,
  baseBrightEnd: 2,
  roughness: 0,
  metallic: 5,
  specularIntensity: 9.6,
  fresnelPower: 5,
  fresnelIntensity: 5,
  iridescence: 2,
  envReflect: 8,
  envBrightness: 10,
  aoStrength: 2.5,
  aoRange: 0.235,
  rimStrength: 2.4,
  rimColor: "#ffffff",
  light1Intensity: 5,
  light1X: 0,
  light1Y: 4,
  light1Z: 5,
  light2Intensity: 0.85,
  light2X: 2,
  light2Y: -8,
  light2Z: 3,
  light3Intensity: 1.1,
  light3X: -0.2,
  light3Y: 6.4,
  light3Z: 0,
  ambientIntensity: 0,
  totalScrollRange: 130,
  scrollSpeed: 1,
  bgColor: BG_HEX,
  textColor: "#1a1a2e",
  textColorLight: "#ffffff",
  textOpacity: 0.7,
  fontSize: 1.1,
  fontWeight: 100,
  letterSpacing: 0.4,
  textBottom: 13,
  emergeDuration: 0.7,
  letterStagger: 0.08,
  textRevealDelay: 0.3,
  textTravelDist: 10,
  menuBtnDelay: 1.3,
  birthDuration: 2,
  birthFloatDist: 100,
  birthSpinSpeed: 2.95,
  birthFadeSpeed: 2,
  birthTextAt: 0.96,
  birthFlyInDist: 45,
  birthFlyInCurve: 8.8,
  birthArcHeight: -15,
  birthStartX: 0,
  birthStartY: -20,
  birthEndX: 0,
  birthEndY: 0,
  birthScaleStart: 4.7,
  birthSpinMult: 0.15,
  birthTiltAmp: 0.125,
  birthTiltSpeed: 1.7,
  birthSpinBurstX: 8,
  birthSpinBurstY: 0,
  birthSpinBurstZ: 0,
  birthUseBezier: 0,
  birthBezierX1: 0.16,
  birthBezierY1: 1,
  birthBezierX2: 0.3,
  birthBezierY2: 1,
  revealRadius: 420,
  revealIntensity: 1.95,
  brushFade: 0.006,
  brushSizeMult: 0.4,
  brushOpacityMult: 0.15,
  brushSpacing: 10,
  brushSmoothing: 0.12,
  brushMaskExpand: 1.001,
  bristleCount: 18,
  bristleAngleSpread: 0,
  bristleDistMin: 0.15,
  bristleDistMax: 0.6,
  bristleSizeMin: 0.25,
  bristleSizeMax: 0.7,
  bristleOpacityMin: 0.4,
  bristleOpacityMax: 1,
  brushCoreSize: 0.76,
  brushCoreOpacity: 0.6,
  brushCoreFalloff: 0.01,
  blobCount: 10,
  blobSizeMin: 0.34,
  blobSizeMax: 1.06,
  blobAlphaMin: 0.17,
  blobAlphaMax: 0.93,
  gradSpeed: 2.6,
  gradScale: 3.5,
  gradColor1: _sc[0],
  gradColor2: _sc[1],
  gradColor3: _sc[2],
  gradColor4: _sc[3],
  glassCubeSize: 3.7,
  glassCornerRadius: 0.24,
  glassFresnelPower: 15,
  glassEdgeAlpha: 3,
  glassSpecular: 3.4,
  glassSpecPower: 150,
  glassIridescence: 1,
  glassRotSpeedX: 0.62,
  glassRotSpeedY: 0.36,
  glassRefraction: 0.5,
  glassBlur: 9.2,
  glassOpacity: 0.92,
  glassRoughness: 0.12,
  glassIor: 1.5,
  glassThickness: 2.5,
  glassClearcoatRoughness: 0.1,
  glassEnvIntensity: 1.5,
  glassEdgeOpacity: 0,
  glassTintR: 1.5,
  glassTintG: 1.5,
  glassTintB: 1.5,
  shatterSpeed: 2,
  shatterSpread: 1,
  shatterFade: 2.5,
  shatterOpacity: 0.35,
  shatterColor: "#d0d4e8",
  shatterDuration: 0.12,
  shatterGravity: 4,
  shatterFadeSpeed: 3,
  explodeDuration: 6,
  explodeCap: 1.2,
  shardSegments: 1,
  shardRotSpeed: 0,
  progressSpinSpeed: 0.2,
  shatterThreshold: 0.15,
  convergenceRange: 0.5,
  convergenceSharpness: 0.23,
  helixRotationMult: 1,
  streamSpeed: 3.1,
  spiralStrength: 0.3,
  dissipateStart: 0.7,
  helixCount: 120000,
  helixLength: 66,
  helixRadius: 2.8,
  helixTurns: 10,
  helixSpread: 0.2,
  helixStartRadius: 0.8,
  helixSizeMin: 0.15,
  helixSizeMax: 0.45,
  helixPointSize: 0.4,
  helixOpacity: 0.7,
  menuBlur: 30,
  menuBgOpacity: 0.2,
  menuTextColor: "#1a1a2e",
  menuInputColor: BG_HEX,
  reticleRange: 1.2,
  reticleMinR: 16,
  reticleMaxR: 50,
  reticleCrossSize: 10,
  reticleOpacity: 0.55,
  reticleSmoothing: 0.08,
  chatStiffness: 4.6,
  chatDamping: 5.7,
  chatReturnStiffness: 5.3,
  chatReturnDamping: 6.9,
  chatArcStiffness: 2.7,
  chatArcDamping: 1.3,
  chatArcKickZ: -5,
  chatArcKickX: -3,
  chatSpinKick: 3.9,
  chatSpinDecay: 2.5,
  pillOffsetX: 280,
  pillOffsetY: 200,
  pillLineColor: "rgba(18,18,40,0.45)",
  pillLineWidth: 0.8,
  glitterCount: 500,
  glitterSizeMin: 0.35,
  glitterSizeMax: 1.7,
  glitterLifetimeMin: 8,
  glitterLifetimeMax: 21,
  glitterDriftMin: 18,
  glitterDriftMax: 120,
  glitterSpread: 105,
  glitterSpawnRate: 50,
  glitterIdleRate: 2,
  glitterFadeExp: 0.6,
  // Timestamp seed used to trigger birth animation replays (change to replay)
  birthReplay: 1775786365506,
  birthEasing: 4.2,

  // ── Smiley face ──
  smileyScale: 0.75,
  smileyOpacity: 0.6,

  // ── Sleep mode ──
  sleepIdleTime: 15,
  sleepRampTime: 3,

  // ── Hold to showcase ──
  holdDuration: 600,
  holdClickThreshold: 150,

  // ── Showcase zoom ──
  showcaseZoomSpeed: 0.5,
  showcaseOpenDelay: 3200,

  // ── Angular velocity ──
  angularDrag: 0.75,
  angularClamp: 8,
  dizzyThreshold: 1.5,

  // ── UI constants ──
  panelBorderRadius: 120,
  panelPadding: 70,
  panelPaddingMobile: 16,
  panelBlur: 50,
};
