export const SHOWCASE_PROJECTS = [
  {
    number: "01",
    title: "Nimbus",
    tag: "AI WEBSITE GENERATOR · 2025",
    text: "Full-stack AI that generates production-ready websites from prompts. Real-time streaming, 60+ design controls, multi-format export. Users describe what they want in natural language and watch their site build itself live, with full control over layout, typography, and color at every step.",
    accent: "#1a8fe0",
    skills: ["React", "Supabase", "Claude API", "Stripe", "Vite"],
    link: "https://nimbuswebsites.com",
    images: [
      "/projects/nimbus1.webp",
      "/projects/nimbus2.webp",
      "/projects/nimbus3.webp",
    ],
  },
  {
    number: "02",
    title: "XSBL",
    tag: "WEB ACCESSIBILITY · 2024",
    text: "Accessibility auditing platform with AI analysis, Slack alerts, and WCAG compliance tracking at scale. Scans pages on a schedule, flags violations by severity, and pushes actionable fixes directly to your team's Slack channels.",
    accent: "#8b5cf6",
    skills: ["React", "AI Analysis", "Slack API", "WCAG"],
    link: "https://xsbl.io",
    images: [
      "/projects/xsbl1.webp",
      "/projects/xsbl2.webp",
      "/projects/xsbl3.webp",
    ],
  },
  {
    number: "03",
    title: "Nimbus WMS",
    tag: "AI WAREHOUSE · 2024",
    text: "Inventory platform with AI demand forecasting, intelligent routing, and native mobile apps. Predicts stock needs weeks ahead using historical sales data, then auto-routes shipments across warehouses to minimize delivery time.",
    accent: "#10b981",
    skills: ["React Native", "AI Forecasting", "Node.js", "PostgreSQL"],
    link: "https://nimbus-landing.netlify.app",
    images: [
      "/projects/nimbuswms1.webp",
      "/projects/nimbuswms2.webp",
      "/projects/nimbuswms3.webp",
    ],
  },
  {
    number: "04",
    title: "Pillow",
    tag: "COMPONENT LIBRARY · 2023",
    text: "Neumorphism React library with soft UI design, customizable theming, and composable API. Ships 30+ components with built-in dark mode, fluid animations, and a token system that lets you reshape the entire look with a single config object.",
    accent: "#f59e0b",
    skills: ["React", "CSS-in-JS", "Theming", "npm"],
    link: "https://pillow-ui.netlify.app",
    images: [
      "/projects/pillow1.webp",
      "/projects/pillow2.webp",
      "/projects/pillow3.webp",
    ],
  },
  {
    number: "05",
    title: "Halo",
    tag: "3D ART · 2023",
    text: "Creative coding — neon text around a 3D object with dynamic lighting in WebGL. Custom GLSL shaders drive the glow and refraction, with the text geometry procedurally wrapping the surface and responding to mouse movement in real time.",
    accent: "#a855f7",
    skills: ["Three.js", "WebGL", "GLSL", "Creative Coding"],
    link: "https://halo-effect.netlify.app",
    images: [
      "/projects/halo1.webp",
      "/projects/halo2.webp",
      "/projects/halo3.webp",
    ],
  },
];
